project:
  type: website
  render:
    - index.qmd
  resources:
    - figs/

metadata-files:
  - ../_shared.yml

format:
  revealjs:
    include-in-header:
      - resources/_header.html
      - ../styles/practice-timer.html
    include-after-body:
      - ../styles/control-buttons.html
      - ../styles/print-footer.html
