project:
  type: website
  render:
    - index.qmd
  resources:
    - figs/
    - resources/elastic-scroll.css
    - resources/s2-html-example.html
    - resources/s2-html-example.css
    - resources/s2-html-example-1.html
    - resources/s2-html-example-2.html
    - resources/s2-html-example-3.html
    - resources/s2-html-example-4.html
    - resources/s2-html-example-5.html
    - resources/s2-html-example-6.html
    - resources/s2-structure-example.css
    - resources/s2-structure-example-1.html
    - resources/s2-structure-example-2.html
    - resources/s2-structure-example-3.html
    - resources/s2-structure-example-4.html

metadata-files:
  - ../_shared.yml

format:
  revealjs:
    include-in-header:
      - resources/_header.html
      - ../styles/practice-timer.html
    include-after-body:
      - ../styles/control-buttons.html
      - ../styles/print-footer.html
